using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class sound : Clickable
{
    ///<summary>
    /*
    The sound.cs is one of the scripts described in the assignment pdf. Here a sound plays whenever the object is clicked. 
    for this assignment the sound clip is a coin pick up sound  generated by the BFxr sound effect software.
    The sound clip is attached in the SceneSpawner as it was assummed that the prefabs i was working with were "empty" in that they were prefabs of base unity classes. 
    */
    ///</summary>

    ///<notes>
    /* So as far as naming convents go. Normally I would make the sound class PascalCase like all other classes.
    however, the i was following the case convention like what was shown in the assignment pdf. 

    
    I was uncertain about if the sound.cs file should be played if the mesh renderer is turned off.
    I added the variable soundPlaysAlways and the resulting logic so that if the variable is true
    the gameObject holding this script will play a sound regardless of if visisble. 
    And if the soundPlaysAlways is false it will only play a sound when visible. 
    */
    ///</notes>
    public bool soundPlaysAlways = true; // I was uncertain about if the sound.
    public override void Clicked()
    {
        if (!soundPlaysAlways)
        {
            if (!GetComponent<MeshRenderer>().enabled)
            {
                // if the sound does not play always and the object is no longer visible. 

                // this is broken appart so this is only evaulated when soundPlaysAlways = false
                // because the GetComponent call is slower. 

                return;
            }
        }

        // otherwise play audio source
        AudioSource audio = GetComponent<AudioSource>();
        audio.PlayOneShot(audio.clip, 1);
    }
}
